const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),out=path.join(root,'test-results');fs.mkdirSync(out,{recursive:true});
(async()=>{
  const browser=await chromium.launch({headless:true,args:['--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream']});
  try{
    const context=await browser.newContext({viewport:{width:1440,height:1050},permissions:['microphone']});
    const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
    await page.goto('http://localhost:4173');
    await page.getByRole('heading',{name:'Make yourself at home.'}).waitFor();
    await page.screenshot({path:path.join(out,'melorina-desktop.png'),fullPage:true});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    await page.locator('[data-start="hello"]').first().click();
    await page.locator('#answer').fill('a different greeting');
    await page.locator('#answer-form').evaluate(form=>form.requestSubmit());
    assert.match(await page.locator('#answer-message').textContent(),/profile hasn’t changed/);
    assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('melorina.v1')||'{"events":[]}').events.length),0);
    await page.locator('[data-hint]').click();
    await page.locator('#answer').fill('marhaba');
    await page.locator('#answer-form').evaluate(form=>form.requestSubmit());
    await page.locator('[data-next]').waitFor();
    await page.locator('#record-details summary').click();
    await page.locator('#record-btn').click();
    await page.getByRole('button',{name:'Stop recording'}).waitFor();
    await page.waitForTimeout(500);
    await page.getByRole('button',{name:'Stop recording'}).click();
    await page.locator('#voice-playback:not([hidden])').waitFor();
    assert.match(await page.locator('#record-status').textContent(),/No pronunciation score/);
    await page.locator('[data-next]').click();
    await page.locator('[data-choice="My name is"]').click();
    await page.locator('[data-next]').click();
    await page.locator('#answer').fill('شُكْرًا');
    await page.locator('#answer-form').evaluate(form=>form.requestSubmit());
    await page.locator('[data-next]').click();
    await page.locator('#answer').fill('marhaba');
    await page.locator('#answer-form').evaluate(form=>form.requestSubmit());
    await page.locator('[data-next]').click();
    // The first hinted greeting created exactly one targeted revisit.
    await page.locator('#answer').fill('مرحبا');
    await page.locator('#answer-form').evaluate(form=>form.requestSubmit());
    await page.locator('[data-next]').click();
    await page.getByRole('heading',{name:'A little more feels familiar.'}).waitFor();
    let state=await page.evaluate(()=>JSON.parse(localStorage.getItem('melorina.v1')));
    assert.equal(state.sessions.length,1);assert.equal(state.events.length,5);
    assert.equal(state.skills['hello:recall'].assisted,1);
    assert.equal(state.skills['hello:recall'].independent,2);
    assert.equal(state.skills['name:recall'],undefined);
    assert.equal(state.skills['hello:pronunciation'],undefined);
    await page.getByRole('button',{name:'See my growth'}).click();
    await page.screenshot({path:path.join(out,'melorina-growth.png'),fullPage:true});
    await page.reload();
    state=await page.evaluate(()=>JSON.parse(localStorage.getItem('melorina.v1')));assert.equal(state.sessions.length,1);
    await page.locator('[data-view="settings"]').first().click();
    await page.locator('#learner-name').fill('Sam <b>');
    await page.locator('#learning-goal').selectOption('Getting around');
    await page.locator('#practice-time').selectOption('5');
    await page.locator('#conversation-goal').fill('Order breakfast near home');
    await page.locator('#settings-form').evaluate(form=>form.requestSubmit());
    await page.locator('[data-view="today"]').first().click();
    assert.equal(await page.getByRole('heading',{name:'Hello, Sam <b>.'}).count(),1);
    await page.locator('[data-view="words"]').click();
    await page.locator('#word-search').fill('water');assert.equal(await page.locator('.word-card').count(),1);
    await page.locator('[data-word="water"]').click();
    await page.locator('[data-hint]').click();
    await page.locator('#answer').fill('maay');await page.locator('#answer-form').evaluate(form=>form.requestSubmit());
    await page.locator('[data-next]').click();
    await page.locator('[data-view="today"]').first().click();
    await page.locator('[data-practice]').click();
    await page.locator('.conversation-panel').waitFor();
    await page.screenshot({path:path.join(out,'melorina-conversation.png'),fullPage:true});
    await page.locator('[data-view="profile"]').first().click();
    const downloadPromise=page.waitForEvent('download');await page.locator('[data-export]').click();
    const download=await downloadPromise;assert.equal(download.suggestedFilename(),'melorina-progress.json');
    // New focus loop: partial clue, full model, bounded repair, then continue.
    await page.locator('[data-view="today"]').first().click();
    await page.locator('[data-focus]').click();
    await page.locator('.focus-ribbon').waitFor();
    assert.match(await page.locator('.page-intro').textContent(),/Order breakfast near home/);
    await page.locator('[data-view="words"]').click();
    await page.locator('#word-search').fill('water');
    await page.locator('[data-focus-word="water"]').click();
    await page.locator('[data-hint]').click();
    await page.getByRole('button',{name:'Show me the whole model'}).click();
    await page.locator('#answer').fill('maay');
    await page.locator('#answer-form').evaluate(form=>form.requestSubmit());
    await page.locator('[data-retry]').click();
    assert.equal(await page.locator('.practice-model').count(),0);
    await page.locator('#answer').fill('maay');
    await page.locator('#answer-form').evaluate(form=>form.requestSubmit());
    assert.match(await page.locator('.feedback').textContent(),/useful rehearsal/);
    assert.equal(await page.locator('[data-retry]').count(),0);
    await page.locator('[data-next]').click();
    const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
    const mp=await mobile.newPage();mp.on('pageerror',e=>errors.push(e.message));await mp.goto('http://localhost:4173');
    await mp.screenshot({path:path.join(out,'melorina-mobile.png'),fullPage:true});
    assert.equal(await mp.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    await mp.locator('[data-start="hello"]').first().click();
    await mp.locator('[data-hint]').click();
    await mp.getByRole('button',{name:'Show me the whole model'}).click();
    await mp.locator('#answer').fill('marhaba');
    await mp.locator('#answer-form').evaluate(form=>form.requestSubmit());
    assert.equal(await mp.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    await mp.locator('[data-retry]').click();
    assert.equal(await mp.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    await mp.screenshot({path:path.join(out,'melorina-mobile-conversation.png'),fullPage:true});
    // Standalone build opens without a web server and keeps the learning controls.
    const standalone=await context.newPage();standalone.on('pageerror',e=>errors.push(e.message));
    await standalone.goto('file://'+path.join(root,'dist/melorina.html'));
    await standalone.locator('[data-start="hello"]').first().click();
    await standalone.locator('#answer').fill('marhaba');await standalone.locator('#answer-form').evaluate(form=>form.requestSubmit());
    await standalone.locator('[data-next]').waitFor();
    assert.deepEqual(errors,[]);
    console.log('PASS: full adaptive flow, progressive hints, rehearsal separation, personal goals, focused practice, recording/replay, saved progress, preferences, search, export, desktop/mobile layout, and standalone build.');
  }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
