(function(root){
'use strict';
const V=root.MelorinaVoiceCore,C=root.MelorinaContent,E=root.MelorinaEngine;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const id=()=>root.crypto?.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);
function create({read,write,goal,update,client=new root.MelorinaVoiceClient()}){
 let page='home',connection=null,consent=false,busy=false,recording=false,capturePurpose=null,pending=null,transcript=null,clip='',message='',drill=null,chat=null,generation=0,pace=null;
 const word=key=>C.words.find(w=>w.id===key),prefs=()=>read().prefs;
 const usable=()=>connection===true&&consent;
 const disabled=()=>!usable()||busy||recording?' disabled':'';
 const speechPrefs=()=>({voice:prefs().voice,tone:prefs().tone,pace:pace||prefs().pace});
 function pauseLocal(){document.querySelector('.voice-local-audio')?.pause?.();}
 function clearClip(){pauseLocal();if(clip)URL.revokeObjectURL(clip);clip='';pending=null;transcript=null;}
 function cancel(){generation++;client.cancel();busy=false;recording=false;clearClip();message='Stopped. No new learning evidence was saved.';update();}
 function leave(){cancel();page='home';drill=null;chat=null;consent=false;message='';}
 async function run(fn){if(busy||recording)return;pauseLocal();const token=generation;busy=true;message='';update();try{await fn(()=>token===generation);}catch(e){if(token===generation)message=e.message;}finally{if(token===generation){busy=false;update();}}}
 async function connect(){if(connection!==null)return;try{const result=await client.request('status');connection=result.configured===true;}catch{connection=false;}update();}
 function enter(wordId){if(wordId)startDrill('spoken',wordId);connect();}
 function options(map,selected){return Object.entries(map).map(([value,label])=>'<option value="'+value+'" '+(value==selected?'selected':'')+'>'+esc(label)+'</option>').join('');}
 function preferencePanel(){const p=prefs();return '<details class="voice-preferences" '+(page==='home'?'open':'')+'><summary>Your voice & conversation style</summary><div class="voice-settings-grid"><label>Voice<select data-v-pref="voice">'+options(Object.fromEntries(V.voices.map(v=>[v,v[0].toUpperCase()+v.slice(1)])),p.voice)+'</select></label><label>Coaching tone<select data-v-pref="tone">'+options(V.tones,p.tone)+'</select></label><label>Speaking pace<select data-v-pref="pace">'+options({'0.75':'Slow and spacious','0.9':'Comfortable','1':'Natural'},p.pace)+'</select></label><label>Conversation version<select data-v-pref="version">'+options(V.versions,p.version)+'</select></label><label>Situation<select data-v-pref="scenario">'+options({hello:'Meet a neighbour',cafe:'Order at a café',directions:'Find the market'},p.scenario)+'</select></label><label>Sound focus<select data-v-pref="sound">'+options(Object.fromEntries(Object.entries(V.sounds).map(([k,v])=>[k,v.label])),p.sound)+'</select></label></div><label class="voice-check"><input type="checkbox" data-v-follow '+(p.followPace?'checked':'')+'> Follow my speaking pace</label><p class="small">After a longer confirmed reply, playback adjusts gently to your speaking pace. Your selected coaching tone stays in your control.</p><button class="secondary" data-v-preview'+disabled()+'>Hear this voice</button><span class="small"> AI-generated voice · Emirati delivery still needs educator review.</span></details>';}
 function setup(){return '<section class="voice-consent"><span class="pill '+(connection?'tone-sage':'tone-peach')+'">'+(connection===null?'Checking voice connection…':connection?'Voice configured':'Voice setup needed')+'</span>'+(connection===false?'<p>Text practice still works. To activate AI voice, run Melorina with an OpenAI API key on your server.</p><details><summary>Local setup</summary><p class="small">Copy <code>.env.example</code> to <code>.env</code>, set <code>OPENAI_API_KEY</code> there, and run <code>npm run start:voice</code>. Open <code>http://localhost:4173</code>. The downloaded HTML alone cannot connect to the voice service. API usage is billed to the configured OpenAI account.</p></details><button class="ghost" data-v-reconnect>Check connection again</button>':'')+'<label class="voice-check"><input type="checkbox" data-v-consent '+(consent?'checked':'')+'> Enable AI voice for this visit</label><p class="small">Audio you choose to transcribe and conversation text are sent to OpenAI for processing. Melorina keeps recordings and conversation history only in this page’s memory; learning evidence stays in this browser. OpenAI processing follows its own data policies. You can stop at any time.</p></section>';}
 function home(){const s=read(),due=Object.values(s.skills).filter(x=>x.due<=Date.now()).length;return '<div class="voice-hero"><div><div class="eyebrow">LISTEN. REACH. REBUILD.</div><h2>Let your words find a voice.</h2><p>One small part, then a real-life exchange. Choose how you want to practice today.</p>'+(due?'<span class="pill tone-sage">'+due+' voice skills ready to revisit</span>':'')+'</div><div class="voice-orb" aria-hidden="true"><span></span><span></span><span></span><span></span><span></span></div></div><div class="voice-paths"><button class="panel voice-path" data-v-start="listening"><span class="eyebrow">TUNE YOUR EAR</span><h3>Listen & recognise</h3><p>Hear a word before seeing it. Discover what your ear remembers.</p></button><button class="panel voice-path" data-v-start="spoken"><span class="eyebrow">FIND YOUR WORDS</span><h3>Say it yourself</h3><p>Speak a word, check the transcript, then bring it into another situation.</p></button><button class="panel voice-path" data-v-start="sound"><span class="eyebrow">ONE SMALL PART</span><h3>Sound workshop</h3><p>Listen slowly, record, compare, and try again. Choose a sound focus above.</p></button></div><section class="panel voice-chat-entry"><div><h3>A conversation that meets you here.</h3><p>Choose a café, a neighbour, or finding your way. Speak or type; ask for help whenever you need it.</p></div><button class="primary" data-v-chat'+disabled()+'>Start a voice conversation</button></section>'+growth()+'<p class="small">AI transcripts can be wrong. They help us practice word recall, but do not measure pronunciation or sound accuracy.</p>';}
 function recorderPanel(purpose){const ownRecording=recording&&capturePurpose===purpose;return '<section class="voice-capture"><div class="button-row"><button class="'+(ownRecording?'primary recording':'secondary')+'" data-v-record="'+purpose+'" '+((!usable()||busy||(recording&&!ownRecording))&&!ownRecording?'disabled':'')+'>'+(ownRecording?'Stop recording':'Record '+(purpose==='command'?'a command':'my voice'))+'</button>'+(busy||recording?'<button class="ghost" data-v-cancel>Cancel</button>':'')+'</div><p class="small">'+(ownRecording?'Recording… maximum 30 seconds. Tap Stop when you finish.':'Tap to record. Nothing is uploaded until you choose Transcribe.')+'</p>'+(pending?.purpose===purpose?'<audio class="voice-local-audio" controls src="'+esc(clip)+'" aria-label="Your recording"></audio><button class="primary" data-v-transcribe'+disabled()+'>Transcribe recording</button><button class="ghost" data-v-discard'+(busy?' disabled':'')+'>Discard</button>':'')+(transcript?.purpose===purpose?'<div class="voice-transcript"><span class="eyebrow">CHECK WHAT WAS HEARD</span><p dir="auto">'+esc(transcript.text)+'</p><p class="small">Is this what you said? A recognition error should not count against your learning.</p><button class="primary" data-v-confirm'+disabled()+'>Yes, use this '+(transcript.purpose==='command'?'command':'transcript')+'</button><button class="ghost" data-v-discard'+(busy?' disabled':'')+'>That is not what I said</button></div>':'')+'</section>';}
 function turn(){const w=word(drill.words[drill.index]),frame=C.practiceFrames[w.id];const isListening=drill.mode==='listening';const title=drill.sound?'Explore a sound in “'+w.meaning+'”':isListening?'What did you hear?':'Say “'+w.meaning.toLowerCase()+'”';
  return '<div class="voice-turn-head"><span class="pill">'+(drill.index+1)+' / 3 moments</span><button class="ghost" data-v-home>Leave this practice</button></div><section class="panel voice-drill"><div class="eyebrow">'+(drill.repair?'SLOW DOWN & REBUILD':drill.index===2?'BRING IT INTO LIFE':drill.index===1?'A LITTLE SPACE':'YOUR NEXT REACH')+'</div><h2>'+esc(title)+'</h2><p>'+esc(drill.index===2?(isListening?'Listen once more after a change of scene. Choose the meaning you hear.':frame.situation):drill.reason)+'</p><div class="button-row"><button class="primary" data-v-listen'+disabled()+'>Listen'+(drill.heard?' again':'')+'</button><button class="ghost" data-v-slower'+disabled()+'>Slower</button><button class="ghost" data-v-reveal'+(busy||recording?' disabled':'')+'>Show the written model</button></div>'+(drill.hinted||drill.feedback?'<div class="voice-model"><span class="arabic" lang="ar" dir="rtl">'+esc(w.ar)+'</span><span>'+esc(w.latin)+' · '+esc(w.meaning)+'</span></div>':'')+(drill.feedback?'<div class="feedback" role="status"><strong>'+esc(drill.feedback.title)+'</strong><p>'+esc(drill.feedback.note)+'</p><div class="voice-chunks">'+frame.chunks.map(c=>'<span><b class="arabic" lang="ar">'+esc(c.ar)+'</b><small>'+esc(c.meaning)+'</small></span>').join('')+'</div><button class="secondary" data-v-phrase'+disabled()+'>Hear the whole phrase</button>'+(!drill.retryUsed?'<button class="secondary" data-v-repair'+(busy||recording?' disabled':'')+'>Hide it & try once more</button>':'')+'<button class="primary" data-v-next'+(busy||recording?' disabled':'')+'>'+(drill.index===2?'See my reflection':'Try the next moment')+'</button></div>':isListening?'<div class="choices">'+[...C.words.filter(x=>x.id!==w.id).slice(0,2),w].map(x=>'<button class="choice" data-v-answer="'+x.id+'" '+(!drill.heard||busy||recording?'disabled':'')+'>'+esc(x.meaning)+'</button>').join('')+(drill.heard?'':'<p class="small">Listen to the audio before choosing.</p>'):recorderPanel('word'))+(drill.sound?'<p class="small">Compare your own recording with the model. This is sound rehearsal; no phoneme score is inferred from a transcript.</p>':'')+'<button class="ghost" data-v-target'+(busy||recording?' disabled':'')+'>Keep this word in my practice</button></section>'+commands();
 }
 function commands(){return '<details class="voice-commands" '+(capturePurpose==='command'&&(pending||transcript||recording||busy)?'open':'')+'><summary>Voice controls</summary><p class="small">Record a command, then confirm it: “repeat”, “slower”, “hint”, “next”, or “stop”. Arabic alternatives include “عيد”, “شوي شوي”, “ساعدني”, “كمل”, and “وقف”. The microphone only listens after you tap.</p>'+recorderPanel('command')+'</details>';}
 function chatView(){return '<div class="voice-turn-head"><span class="pill">'+chat.turns+' / 6 replies · '+esc(V.versions[prefs().version])+'</span><button class="ghost" data-v-end>End conversation</button></div><section class="panel voice-conversation"><div class="voice-messages" aria-live="polite">'+chat.messages.map(m=>m.role==='user'?'<div class="voice-bubble learner"><span class="small">You</span><p dir="auto">'+esc(m.text)+'</p></div>':'<div class="voice-bubble tutor"><span class="small">Melorina · AI conversation partner</span><p class="arabic" lang="ar" dir="rtl">'+esc(m.reply.arabic)+'</p><details data-v-translation><summary>Meaning & reading help</summary><p>'+esc(m.reply.latin)+'</p><p>'+esc(m.reply.english)+'</p></details>'+(m.reply.feedback?'<p class="voice-coach-note">'+esc(m.reply.feedback)+'</p>':'')+'</div>').join('')+'</div>'+(chat.reply?'<div class="button-row"><button class="secondary" data-v-chat-listen'+disabled()+'>Listen to the reply</button><button class="ghost" data-v-slower'+disabled()+'>Slower</button><button class="ghost" data-v-help'+disabled()+'>I need a little help</button></div>':'')+(chat.turns<6?recorderPanel('chat')+'<form id="voice-chat-form"><label for="voice-chat-input">Or type your reply</label><div class="voice-compose"><input class="answer-input" id="voice-chat-input" dir="auto" maxlength="600" placeholder="Find your words…" value="'+esc(chat.draft)+'"><button class="primary" type="submit"'+disabled()+'>Send</button></div></form>':'<p>That is six exchanges. Pause, reflect, and practice one useful word.</p><button class="primary" data-v-end>Finish & reflect</button>')+(chat.reply?.focusWord&&chat.reply.focusWord!=='none'?'<button class="ghost" data-v-chat-focus>Practice “'+esc(word(chat.reply.focusWord).meaning)+'” from this conversation</button>':'')+'</section>'+commands();}
 function reflection(){const count=read().events.filter(e=>e.session===drill?.session).length,rehearsals=read().rehearsals.filter(e=>e.session===drill?.session).length;return '<section class="panel completion"><h2>A little more belongs to you.</h2><p>'+count+' listening or spoken-word attempts and '+rehearsals+' rehearsals saved separately.</p><p>Take a break. Later practice helps us see what stayed with you.</p><button class="primary" data-v-home>Back to my voice studio</button></section>';}
 function growth(){const rows=Object.values(read().skills);if(!rows.length)return '';return '<section class="panel voice-growth"><h3>Your voice practice, one word at a time.</h3>'+rows.map(s=>'<div class="evidence-row"><div><strong>'+esc(word(s.word).meaning)+' · '+(s.mode==='listening'?'Listening recognition':'Spoken word recall')+'</strong><small>'+s.independent+' without help · '+s.assisted+' with help · '+s.delayed+' delayed revisits</small></div><span class="pill '+(s.lastOutcome==='independent'?'tone-sage':'tone-peach')+'">'+(s.lastOutcome==='independent'?'Building familiarity':'A little more support')+'</span></div>').join('')+'</section>';}
 function render(){return '<div class="page-intro"><div class="eyebrow muted">YOUR VOICE, YOUR RHYTHM</div><h1>Make room for your voice.</h1><p>'+esc(goal().conversationGoal||'Everyday Emirati Arabic, with room to listen, pause, and try again.')+'</p></div>'+setup()+preferencePanel()+'<div class="voice-status" role="status" aria-live="polite">'+esc(message||(busy?'Working on that…':recording?'Listening…':''))+'</div>'+(page==='home'?home():page==='drill'?turn():page==='chat'?chatView():reflection())+(busy&&!recording?'<button class="ghost" data-v-cancel>Stop this request</button>':'');}
 function resetTurn(){const w=word(drill.words[drill.index]);drill.hinted=drill.sound;drill.heard=false;drill.plays=0;drill.feedback=null;drill.repair=false;drill.retryUsed=false;drill.event=id();const skill=read().skills[w.id+':'+drill.mode];pace=skill&&skill.lastOutcome!=='independent'?0.75:null;clearClip();}
 function startDrill(mode,wordId){client.cancel();generation++;busy=false;recording=false;clearClip();const p=V.plan(read(),mode==='listening'?'listening':'spoken',goal().goal,wordId);drill={...p,mode:mode==='listening'?'listening':'spoken',sound:mode==='sound',index:0,session:id()};resetTurn();page='drill';message='';update();}
 async function listen(phrase=false){if(!usable())return;return run(async alive=>{const w=word(drill.words[drill.index]);if(drill.mode==='spoken'&&!drill.feedback)drill.hinted=true;const played=await client.speak({...speechPrefs(),wordId:w.id,phrase});if(alive()&&played){drill.heard=true;drill.plays++;if(drill.mode==='listening'&&drill.plays>1)drill.hinted=true;}});}
 function recordEvidence(outcome,extra){const w=word(drill.words[drill.index]);write(V.observe(read(),{id:drill.event,word:w.id,mode:drill.mode,session:drill.session,outcome,assisted:drill.hinted,repair:drill.repair||drill.sound,...extra}));}
 function answerListening(answer){if(!usable()||!drill.heard||drill.feedback||busy||recording)return;const w=word(drill.words[drill.index]),correct=w.id===answer;recordEvidence(correct?(drill.hinted?'assisted':'independent'):'miss',{heard:true});drill.feedback={title:correct?'You made the connection.':'Let’s notice that word.',note:'The audio was “'+w.meaning.toLowerCase()+'”. Listen to the small part, then bring it back.'};update();}
 async function startRecording(purpose){
  if(recording){client.stopRecording();return;}if(!usable()||busy)return;
  clearClip();capturePurpose=purpose;await run(async alive=>{const result=await client.record(status=>{if(!alive())return;recording=status==='recording';message=status==='permission'?'Waiting for microphone permission…':'';update();});if(!alive())return;recording=false;if(result){pending={...result,purpose};clip=URL.createObjectURL(result.blob);}});
 }
 async function transcribe(){if(!pending||!usable())return;return run(async alive=>{const result=await client.request('transcribe',pending.blob,true,pending.purpose==='command'?'command':'practice');if(!alive())return;if(!result.text.trim())throw Error('No clear speech was found. Try recording again. Nothing was scored.');transcript={text:result.text,seconds:pending.seconds,purpose:pending.purpose};pending=null;});}
 function confirm(){if(!transcript||busy||recording||!usable())return;const t=transcript;if(prefs().followPace&&t.text.trim().split(/\s+/).length>=4)pace=V.paceFromSpeech(prefs(),t.text,t.seconds);clearClip();if(t.purpose==='command')return applyCommand(V.command(t.text));if(t.purpose==='chat')return sendChat(t.text);
  const w=word(drill.words[drill.index]);if(E.matches(w,t.text)){recordEvidence(drill.hinted?'assisted':'independent',{confirmed:true});drill.feedback={title:drill.repair||drill.sound?'A useful rehearsal.':'Your word came through.',note:'Your confirmed transcript matches this practice word. That is evidence of word recall, not a pronunciation score.'};}else{drill.feedback={title:'Let’s check the small part.',note:'The transcript did not match this practice word. It may be another valid expression or a speech-recognition error. No miss was recorded. Compare the model and try again.'};}update();
 }
 function repair(){if(!drill.feedback||drill.retryUsed)return;clearClip();drill.retryUsed=true;drill.repair=true;drill.hinted=false;drill.heard=false;drill.plays=0;drill.feedback=null;drill.event=id();update();}
 function next(){if(!drill?.feedback){message='Try this moment first, or leave the practice when you want.';update();return;}client.cancel();clearClip();if(drill.index===2){write({...read(),sessions:[...read().sessions,{id:drill.session,at:Date.now(),mode:drill.mode}].slice(-100)});page='reflection';}else{drill.index++;resetTurn();}update();}
 function chatFocus(){return [...new Set([...read().targets,...(goal().wordTargets||[]),...Object.values(read().skills).filter(s=>s.lastOutcome!=='independent'||s.due<=Date.now()).map(s=>s.word)])].slice(0,3);}
 async function sendChat(text){if(!usable()||busy||recording||chat?.turns>=6)return;const clean=String(text||'').trim();if(clean.length>600)return;const history=chat.messages.map(m=>({role:m.role,text:m.role==='user'?m.text:m.reply.arabic}));if(clean)history.push({role:'user',text:clean});
  await run(async alive=>{const reply=await client.request('conversation',{...prefs(),goal:goal().conversationGoal,history,focus:chatFocus(),helpRequests:chat.helpRequests});if(!alive())return;if(clean){chat.messages.push({role:'user',text:clean});chat.turns++;}chat.messages.push({role:'assistant',reply});chat.reply=reply;chat.draft='';update();try{await client.speak({...speechPrefs(),text:reply.arabic});}catch(e){if(alive())message=e.message+' You can still read the reply.';}});
 }
 function startChat(){if(!usable()||busy||recording)return;client.cancel();generation++;clearClip();page='chat';pace=null;chat={messages:[],reply:null,turns:0,helpRequests:0,draft:''};update();sendChat('');}
 function applyCommand(command){if(command==='stop'){cancel();return;}if(command==='slower'){pace=0.75;message='A little slower.';update();return;}if(command==='repeat'){if(page==='drill')listen();else if(chat?.reply)run(()=>client.speak({...speechPrefs(),text:chat.reply.arabic}));return;}if(command==='hint'){if(page==='drill'){drill.hinted=true;update();}else if(page==='chat'){chat.helpRequests++;sendChat('Please help me with one small part and a short example.');}return;}if(command==='next'&&page==='drill')return next();message=command?'That command is not available in this moment.':'I did not recognise that control. Try “repeat”, “slower”, “hint”, “next”, or “stop”.';update();}
 function bind(){
  const one=(s,event,fn)=>document.querySelector(s)?.addEventListener(event,fn),all=(s,event,fn)=>document.querySelectorAll(s).forEach(el=>el.addEventListener(event,()=>fn(el)));
  one('[data-v-consent]','change',e=>{consent=e.target.checked;if(!consent)cancel();update();});
  one('[data-v-reconnect]','click',()=>{connection=null;connect();update();});
  all('[data-v-pref]','change',el=>{const p={...prefs(),[el.dataset.vPref]:el.dataset.vPref==='pace'?Number(el.value):el.value};write({...read(),prefs:V.preferences(p)});pace=null;});
  one('[data-v-follow]','change',e=>write({...read(),prefs:{...prefs(),followPace:e.target.checked}}));
  all('[data-v-start]','click',el=>startDrill(el.dataset.vStart));
  one('[data-v-chat]','click',startChat);
  one('[data-v-preview]','click',()=>run(()=>client.speak({...speechPrefs(),wordId:'hello'})));
  one('[data-v-listen]','click',()=>listen());one('[data-v-phrase]','click',()=>listen(true));
  all('[data-v-slower]','click',()=>{pace=0.75;message='Playback pace is now slow and spacious.';update();});
  one('[data-v-reveal]','click',()=>{drill.hinted=true;update();});
  all('[data-v-answer]','click',el=>answerListening(el.dataset.vAnswer));
  all('[data-v-record]','click',el=>startRecording(el.dataset.vRecord));
  all('[data-v-cancel]','click',cancel);
  one('[data-v-transcribe]','click',transcribe);one('[data-v-confirm]','click',confirm);
  all('[data-v-discard]','click',()=>{clearClip();message='Recording discarded. Your learning evidence has not changed.';update();});
  one('[data-v-repair]','click',repair);one('[data-v-next]','click',next);
  one('[data-v-target]','click',()=>{write(V.target(read(),drill.words[drill.index]));message='This word will guide future practice.';update();});
  all('[data-v-home]','click',()=>{cancel();page='home';message='';update();});
  one('[data-v-chat-listen]','click',()=>run(()=>client.speak({...speechPrefs(),text:chat.reply.arabic})));
  one('[data-v-help]','click',()=>{chat.helpRequests++;sendChat('Please help me with one small part and a short example.');});
  one('#voice-chat-input','input',e=>{chat.draft=e.target.value;});
  one('#voice-chat-form','submit',e=>{e.preventDefault();if(chat.draft.trim())sendChat(chat.draft);});
  all('[data-v-translation]','toggle',el=>{if(el.open&&!el.dataset.counted){chat.helpRequests++;el.dataset.counted='yes';}});
  one('[data-v-chat-focus]','click',()=>{const key=chat.reply.focusWord;write(V.target(read(),key));startDrill('spoken',key);});
  one('[data-v-end]','click',()=>{cancel();page='home';chat=null;message='Conversation finished. Choose one useful word to revisit later; conversation transcripts are not proficiency scores.';update();});
 }
 return {render,bind,enter,leave,growth,startDrill};
}
root.MelorinaVoiceUI={create};
})(typeof globalThis!=='undefined'?globalThis:this);
